apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-dev
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /srv/share-dev
    server: k8scp
  volumeMode: Filesystem
