apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: website
spec:
  containers:
  - name: myapp
    image: gurve/task1_nonroot:v0.2.0
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
    ports:
      - name: http
        containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: http
        