apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: website
spec:
  replicas: 3
  strategy: 
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gurve/task1_nonroot:v0.2.0
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        ports:
          - name: http
            containerPort: 80